# config/settings/production.yml
application:
  environment: "production"
  debug: false

database:
  host: "${DB_HOST}"
  port: "${DB_PORT}"
  name: "${DB_NAME}"
  username: "${DB_USERNAME}"
  ssl_mode: "require"

api:
  odds_providers:
    - name: "sportradar"
      enabled: true
    - name: "odds_api"
      enabled: true

feature_flags:
  model_retraining: false
  data_collection: true
  experimental_features: false

security:
  rate_limiting:
    requests_per_minute: 100
    burst_limit: 50

monitoring:
  enabled: true
  alerting_threshold: 0.8