name: Code Quality Checks

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort
    
    - name: Check code formatting with Black
      run: black --check .
    
    - name: Check import sorting
      run: isort --check-only .
    
    - name: Type checking with MyPy
      run: |
        pip install mypy
        mypy .
    
    - name: Static code analysis
      run: |
        pip install pylint
        pylint **/*.py