name: Security Scanning

on:
  schedule:
    - cron: '0 2 * * 1'  # Weekly on Monday at 2 AM
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    
    - name: Install security tools
      run: |
        pip install safety bandit
        pip install -r requirements.txt
    
    - name: Run Bandit security linter
      run: bandit -r . -f custom
    
    - name: Check for known vulnerabilities
      run: safety check
    
    - name: Dependency vulnerability scan
      uses: pyupio/safety@master